server:
  port: 8080

spring:
  application:
    name: stocks
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
  h2:
    console:
      enabled: true

liquibase:
  enabled: true
